substitutions:
  _SERVICE: haro-api
  _REGION: us-central1
  _AR_REPO: haro-api
  _IMAGE: haro-api
  _CLOUDSQL_INSTANCE: PROJECT_ID:REGION:INSTANCE_NAME
  _DB_NAME: postgres
  _DB_USER: HARODB
  _SPRING_PROFILES_ACTIVE: cloudrun

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$SHORT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$SHORT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        DB_URL="jdbc:postgresql:///${_DB_NAME}?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=${_CLOUDSQL_INSTANCE}&cloudSqlRefreshStrategy=lazy"

        gcloud run deploy ${_SERVICE} \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --image ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$SHORT_SHA \
          --add-cloudsql-instances ${_CLOUDSQL_INSTANCE} \
          --set-env-vars "SPRING_PROFILES_ACTIVE=${_SPRING_PROFILES_ACTIVE},DB_USERNAME=${_DB_USER},DB_URL=${DB_URL}" \
          --set-secrets "DB_PASSWORD=DB_PASSWORD:latest,JWT_SECRET=JWT_SECRET:latest,AUTH_PEPPER=AUTH_PEPPER:latest"

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$SHORT_SHA
