spring.main.banner-mode=console
spring.banner.charset=UTF-8
spring.application.name=HARO

spring.datasource.url=jdbc:postgresql://192.168.196.168:5432/postgres?useSSL=false&serverTimezone=UTC
spring.datasource.username=casaos
spring.datasource.password=casaos
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Usuario en memoria para pruebas
spring.security.user.name=admin
spring.security.user.password=admin123

server.port=8081

