spring.main.banner-mode=console
spring.banner.charset=UTF-8
spring.application.name=HARO

spring.datasource.url=jdbc:postgresql://192.168.196.168:5432/postgres?useSSL=false&serverTimezone=UTC
spring.datasource.username=casaos
spring.datasource.password=casaos
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Usuario en memoria para pruebas
spring.security.user.name=admin
spring.security.user.password=admin123

server.port=8081

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nicolasmachado19292@gmail.com
spring.mail.password=zjuordgwthcckrrm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# timeouts para evitar cortes raros
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# MUY IMPORTANTE en Gmail personal:
app.verification.from=nicolasmachado19292@gmail.com

